#!/usr/bin/env python3
"""Generate ASHRAE 140-2023 Section 9a (CE100–CE200) case YAML files.

Single source of truth for the 14 HVAC BESTEST cooling-equipment cases. Each
case is a variation of the CE100 base (single adiabatic zone, window-AC DX
system) differing only in weather file, cooling setpoint, and the internal
gain (sensible + latent). The DX performance map (CapFT / EIRFT, transcribed
from CE100MAP.xls Table 26c) and all geometry/HVAC hardware are identical
across cases.

Authoritative parameters extracted from the standard's normative materials:
  - internal gains: OTHER EQUIPMENT objects in the EnergyPlus reference IDFs
  - ODB / EDB per case: DOE-2/NREL reference input LINE-3 descriptions
  - weather dry-bulb: CE1xxA.TM2 (constant-value synthetic files)

Run:  python3 140_tests/scripts/generate_ce_cases.py
"""

import os

HERE = os.path.dirname(os.path.abspath(__file__))
CASES_DIR = os.path.join(os.path.dirname(HERE), "cases")

# case -> (weather, cooling_setpoint_C, sensible_W, latent_W)
CASES = {
    "CE100": ("CE100A", 22.2, 5400, 0),
    "CE110": ("CE110A", 22.2, 5400, 0),
    "CE120": ("CE110A", 26.7, 5400, 0),
    "CE130": ("CE100A", 22.2, 270, 0),
    "CE140": ("CE110A", 22.2, 270, 0),
    "CE150": ("CE110A", 22.2, 5400, 1100),
    "CE160": ("CE110A", 26.7, 5400, 1100),
    "CE165": ("CE165A", 23.3, 5400, 1100),
    "CE170": ("CE110A", 22.2, 2100, 1100),
    "CE180": ("CE110A", 22.2, 2100, 4400),
    "CE185": ("CE100A", 22.2, 2100, 4400),
    "CE190": ("CE110A", 22.2, 270, 550),
    "CE195": ("CE100A", 22.2, 270, 550),
    "CE200": ("CE200A", 26.7, 6120, 1817),
}

# DX performance map (CE100MAP.xls Table 26c, gross SI). Axis 0 = entering
# wet-bulb, axis 1 = outdoor dry-bulb. CapFT normalized to rated (8181.3 W @
# 35C ODB / 19.44C EWB); EIRFT is raw compressor/gross-capacity (the coil
# auto-normalizes it to 1.0 at rated).
CURVES = """performance_curves:

  - name: CE DX CapFT
    table:
      axes:
        - variable: indoor_wet_bulb
          values: [15.0000, 17.2222, 19.4444, 21.6667]
          extrapolation: linear
        - variable: outdoor_dry_bulb
          values: [29.4444, 32.2222, 35.0000, 37.7778, 40.5556, 46.1111]
          extrapolation: linear
      values:
        - [0.90689, 0.88540, 0.86033, 0.83884, 0.81377, 0.76363]
        - [0.97851, 0.95344, 0.92837, 0.90331, 0.87465, 0.82094]
        - [1.05730, 1.02865, 1.00000, 0.97135, 0.93912, 0.88182]
        - [1.13609, 1.10386, 1.07521, 1.03939, 1.00716, 0.94270]
      output_min: 0.0

  - name: CE DX EIRFT
    table:
      axes:
        - variable: indoor_wet_bulb
          values: [15.0000, 17.2222, 19.4444, 21.6667]
          extrapolation: linear
        - variable: outdoor_dry_bulb
          values: [29.4444, 32.2222, 35.0000, 37.7778, 40.5556, 46.1111]
          extrapolation: linear
      values:
        - [0.21834, 0.23330, 0.25147, 0.26957, 0.29139, 0.33773]
        - [0.20736, 0.22306, 0.23830, 0.25574, 0.27670, 0.31863]
        - [0.19769, 0.21270, 0.22735, 0.24412, 0.26291, 0.30217]
        - [0.18935, 0.20374, 0.21713, 0.23284, 0.25000, 0.28655]
      output_min: 0.0
"""


def wall(name, verts):
    v = "\n".join(f"      - {{x: {x}, y: {y}, z: {z}}}" for x, y, z in verts)
    return v


def make_yaml(case, weather, cool_sp, sens_w, lat_w):
    power = sens_w + lat_w
    lf = (lat_w / power) if power > 0 else 0.0
    z = f"{case} Zone"
    return f"""# ASHRAE Standard 140-2023 — Case {case}
# Section 9a: Cooling Equipment (HVAC BESTEST) — GENERATED by
# 140_tests/scripts/generate_ce_cases.py; do not edit by hand.
#
# Weather {weather} (ODB constant), cooling setpoint {cool_sp} C,
# internal gain {power} W ({sens_w} W sensible + {lat_w} W latent).
# Adiabatic single-zone shell; window-AC DX system (8181 W gross, condenser
# fan 108 W, cycling supply fan). February totals compared to the analytical
# solution (CE100MAP.xls / Std140_CE_a_Results.xlsx).

simulation:
  timesteps_per_hour: 1
  start_month: 1
  start_day: 1
  end_month: 3
  end_day: 31

weather_files:
  - "{weather}.csv"

simple_constructions:
  - name: Adiabatic Wall
    u_factor: 0.01
    thickness: 0.01
    thermal_capacity: 0.0
    solar_absorptance: 0.1
    thermal_absorptance: 0.9
    roughness: rough

zones:
  - name: {z}
    volume: 129.6
    floor_area: 48.0

equipment:
  - name: {case} Internal Load
    zones: [{z}]
    power: {power:.1f}
    radiant_fraction: 0.0
    latent_fraction: {lf:.6f}

surfaces:
  - name: {case} North Wall
    zone: {z}
    type: wall
    construction: Adiabatic Wall
    boundary: outdoor
    vertices:
{wall(case, [(8.0,6.0,0.0),(0.0,6.0,0.0),(0.0,6.0,2.7),(8.0,6.0,2.7)])}
  - name: {case} South Wall
    zone: {z}
    type: wall
    construction: Adiabatic Wall
    boundary: outdoor
    vertices:
{wall(case, [(0.0,0.0,0.0),(8.0,0.0,0.0),(8.0,0.0,2.7),(0.0,0.0,2.7)])}
  - name: {case} East Wall
    zone: {z}
    type: wall
    construction: Adiabatic Wall
    boundary: outdoor
    vertices:
{wall(case, [(8.0,0.0,0.0),(8.0,6.0,0.0),(8.0,6.0,2.7),(8.0,0.0,2.7)])}
  - name: {case} West Wall
    zone: {z}
    type: wall
    construction: Adiabatic Wall
    boundary: outdoor
    vertices:
{wall(case, [(0.0,6.0,0.0),(0.0,0.0,0.0),(0.0,0.0,2.7),(0.0,6.0,2.7)])}
  - name: {case} Roof
    zone: {z}
    type: roof
    construction: Adiabatic Wall
    boundary: outdoor
    vertices:
{wall(case, [(0.0,0.0,2.7),(8.0,0.0,2.7),(8.0,6.0,2.7),(0.0,6.0,2.7)])}
  - name: {case} Floor
    zone: {z}
    type: floor
    construction: Adiabatic Wall
    boundary: outdoor
    vertices:
{wall(case, [(0.0,6.0,0.0),(8.0,6.0,0.0),(8.0,0.0,0.0),(0.0,0.0,0.0)])}

air_loops:
  - name: Window AC
    controls:
      cooling_supply_temp: 13.0
      heating_supply_temp: 40.0
      cycling: proportional
      deadband: 1.0
      minimum_damper_position: 0.0
      design_zone_flow: 0.51
      cooling_part_load_cd: 0.229    # HVAC BESTEST CDF = 0.771 + 0.229*PLR
    equipment:
      - type: cooling_coil
        name: {case} DX Cooling Coil
        source: dx
        capacity: 8181.3
        cop: 4.3986
        shr: 0.7774
        rated_airflow: 0.4248
        setpoint: 13.0
        condenser_fan_power: 108.0
        cap_ft_curve: "CE DX CapFT"
        eir_ft_curve: "CE DX EIRFT"
      - type: fan
        name: {case} Supply Fan
        source: on_off
        design_flow_rate: 0.425
        pressure_rise: 271.0
        motor_efficiency: 1.0
        impeller_efficiency: 0.5
        motor_in_airstream_fraction: 1.0
    zones:
      - zone: {z}

zone_groups:
  - name: {case} Zone Group
    zones:
      - {z}

thermostats:
  - name: {case} Thermostat
    zones: [{case} Zone Group]
    cooling_setpoint: {cool_sp}
    heating_setpoint: 10.0

outputs:
  - file: "zone_results.csv"
    frequency: hourly
    variables:
      - "zone:temperature"
      - "zone:humidity_ratio"
  - file: "hvac_results.csv"
    frequency: hourly
    variables:
      - "component:compressor_power"
      - "component:condenser_fan_power"
      - "component:electric_power"
      - "component:total_load"
      - "component:sensible_load"
      - "component:latent_load"

summary_report: true

{CURVES}"""


def main():
    for case, (weather, sp, sens, lat) in CASES.items():
        path = os.path.join(CASES_DIR, f"ashrae140_case{case}.yaml")
        with open(path, "w") as f:
            f.write(make_yaml(case, weather, sp, sens, lat))
        print(f"wrote {os.path.basename(path)}")


if __name__ == "__main__":
    main()
