#!/usr/bin/env python3
"""Generate ASHRAE 140-2023 Section 11 (AE) single-zone air-system cases.

AE200 series (AE201-AE245): a single adiabatic zone with an imposed sensible +
latent load, served by a constant-volume single-zone air handler — outdoor-air
mixing, hot-water (ideal electric) heating coil, chilled-water cooling coil, and
a supply fan. Supply temperature is reset to hold the zone (SingleZone SAT), so
the coils modulate to meet the load. Steady-state: the last simulated hour is
compared to the quasi-analytical solution.

Parameters from the reference EnergyPlus inputs. Run:
    python3 140_tests/scripts/generate_ae_cases.py
"""

import os

HERE = os.path.dirname(os.path.abspath(__file__))
CASES_DIR = os.path.join(os.path.dirname(HERE), "cases")

# case -> dict(weather, sensible gain [W, signed], economizer)
LATENT_W = 586.1
# sp = zone thermostat setpoint [°C]. Both heating and cooling setpoints are set
# equal to this per-case value (from the reference EnergyPlus Clg/Htg-SetP-Sch),
# so the SingleZone SAT reset pins the zone exactly there — the quasi-analytical
# solution reports the zone settling at this temperature for each case.
# return_fan: the AE200 single-zone air handler has supply AND return fans; the
# AE100 fan-coil air handler has a supply fan only. The return fan heats the
# return air before it mixes with outdoor air, so omitting it lowers the coil
# entering temperature (and hence the coil load) slightly.
CASES = {
    # AE100 — fan-coil air handler (supply fan only, no return fan, no economizer)
    "AE101": dict(w="AE_m29", sens=-2931.0, sp=21.111, econ=None, return_fan=False),
    "AE103": dict(w="AE_155", sens=1465.0, sp=23.333, econ=None, return_fan=False),
    "AE104": dict(w="AE_269", sens=2931.0, sp=23.889, econ=None, return_fan=False),
    # AE200 — single-zone air handler (supply + return fans)
    "AE201": dict(w="AE_m29", sens=-2931.0, sp=21.111, econ=None),
    "AE203": dict(w="AE_155", sens=1465.0, sp=23.333, econ=None),
    "AE204": dict(w="AE_269", sens=2931.0, sp=23.889, econ=None),
    "AE205": dict(w="AE_249", sens=1465.0, sp=23.333, econ=None),
    "AE206": dict(w="AE_230", sens=1465.0, sp=23.333, econ=None),
    "AE226": dict(w="AE_230", sens=1465.0, sp=23.333, econ="differential_dry_bulb"),
    "AE245": dict(w="AE_249", sens=1465.0, sp=23.333, econ="differential_enthalpy"),
}

WALLS = [
    ("N", "wall", [(8, 6, 0), (0, 6, 0), (0, 6, 2.7), (8, 6, 2.7)]),
    ("S", "wall", [(0, 0, 0), (8, 0, 0), (8, 0, 2.7), (0, 0, 2.7)]),
    ("E", "wall", [(8, 0, 0), (8, 6, 0), (8, 6, 2.7), (8, 0, 2.7)]),
    ("W", "wall", [(0, 6, 0), (0, 0, 0), (0, 0, 2.7), (0, 6, 2.7)]),
    ("Roof", "roof", [(0, 0, 2.7), (8, 0, 2.7), (8, 6, 2.7), (0, 6, 2.7)]),
    ("Floor", "floor", [(0, 6, 0), (8, 6, 0), (8, 0, 0), (0, 0, 0)]),
]


def surfaces(case):
    z = f"{case} Zone"
    out = []
    for name, typ, v in WALLS:
        verts = ",".join(f"{{x: {x}.0, y: {y}.0, z: {zz}}}" for x, y, zz in v)
        out.append(f"  - {{name: {case} {name}, zone: {z}, type: {typ}, "
                   f"construction: Adiabatic Wall, boundary: adiabatic, vertices: [{verts}]}}")
    return "\n".join(out)


def make_yaml(case, c):
    z = f"{case} Zone"
    # Heating and cooling never occur together in an AE case, so give each case
    # only its active coil — this avoids two-coil heating/cooling mode conflicts
    # in the single-zone controller while giving the same coil loads.
    if c["sens"] < 0:
        coil_block = f"""      - type: heating_coil
        name: {case} Heating Coil
        source: electric
        capacity: 20000.0
        efficiency: 1.0
        setpoint: 45.0
"""
    else:
        coil_block = f"""      - type: cooling_coil
        name: {case} Cooling Coil
        source: chilled_water
        capacity: 20000.0
        shr: 0.75
        rated_airflow: 0.28317
        setpoint: 14.0
        design_water_flow_rate: 0.0015
        design_water_inlet_temp: 5.0
        design_water_outlet_temp: 12.0
        autocalculate_shr: true
"""
    econ_block = ""
    if c["econ"]:
        econ_block = f"""      economizer:
        economizer_type: {c['econ']}
        high_limit: 24.0
"""
    return_fan_block = ""
    if c.get("return_fan", True):
        return_fan_block = """      return_fan_pressure_rise: 249.0
      return_fan_total_efficiency: 0.7
"""
    return f"""# ASHRAE 140-2023 Section 11 — Case {case} (single-zone air system)
# GENERATED by 140_tests/scripts/generate_ae_cases.py.
# Weather {c['w']}, imposed load {c['sens']} W sensible + {LATENT_W} W latent,
# economizer={c['econ']}. Steady-state; compare last hour to QAS.

simulation:
  timesteps_per_hour: 1
  start_month: 1
  start_day: 1
  end_month: 1
  end_day: 7

weather_files:
  - "../weather/{c['w']}.epw"

simple_constructions:
  - name: Adiabatic Wall
    u_factor: 0.01
    thickness: 0.01
    thermal_capacity: 0.0
    solar_absorptance: 0.1
    thermal_absorptance: 0.9
    roughness: rough

zones:
  - name: {z}
    volume: 129.6
    floor_area: 48.0

equipment:
  - name: {case} Sensible Gain
    zones: [{z}]
    power: {c['sens']}
    radiant_fraction: 0.0
    latent_fraction: 0.0
  - name: {case} Latent Gain
    zones: [{z}]
    power: {LATENT_W}
    radiant_fraction: 0.0
    latent_fraction: 1.0

surfaces:
{surfaces(case)}

air_loops:
  - name: SZ Air System
    controls:
      heating_supply_temp: 45.0
      cooling_supply_temp: 14.0
      cycling: on_off
      deadband: 0.2
      minimum_damper_position: 0.3333
      design_zone_flow: 0.34
      fan_operating_mode: continuous
      cooling_sat_reset:
        type: single_zone
        sat_min: 4.0
        sat_max: 50.0
{return_fan_block}{econ_block}    equipment:
{coil_block}      - type: fan
        name: {case} Supply Fan
        source: constant_volume
        design_flow_rate: 0.28317
        pressure_rise: 498.0
        motor_efficiency: 1.0
        impeller_efficiency: 0.7
        motor_in_airstream_fraction: 1.0
    zones:
      - zone: {z}

zone_groups:
  - name: {case} Zone Group
    zones: [{z}]

thermostats:
  - name: {case} Thermostat
    zones: [{case} Zone Group]
    heating_setpoint: {c['sp']}
    cooling_setpoint: {c['sp']}

outputs:
  - file: "hvac_results.csv"
    frequency: hourly
    variables:
      - "component:thermal_output"
      - "component:sensible_load"
      - "component:latent_load"
      - "component:total_load"
      - "component:outlet_temperature"
      - "component:outlet_humidity_ratio"
      - "component:inlet_temperature"
  - file: "zone_results.csv"
    frequency: hourly
    variables:
      - "zone:temperature"
      - "zone:humidity_ratio"

summary_report: true
"""


def main():
    for case, c in CASES.items():
        with open(os.path.join(CASES_DIR, f"ashrae140_case{case}.yaml"), "w") as f:
            f.write(make_yaml(case, c))
        print(f"wrote ashrae140_case{case}.yaml")


if __name__ == "__main__":
    main()
