#!/usr/bin/env python3
"""Generate ASHRAE 140-2023 Section 11 two-zone terminal-reheat cases.

AE300 (constant-volume terminal reheat) and AE400 (VAV terminal reheat): two
adiabatic zones, each with an imposed sensible + latent load, served by a central
air handler — outdoor-air mixing, an electric preheat coil (holds 7.22 C), a
chilled-water cooling coil at a fixed scheduled SAT (12.78 C), and supply/return
fans — plus a per-zone VAV:Reheat terminal (electric reheat) that trims the cold
deck to hold each zone. AE300 boxes run constant volume (min flow fraction 1.0);
AE400 boxes throttle to a minimum flow, then reheat.

The validated outputs are the central-coil loads (preheat + cooling
sensible/latent/total); the zone reheat loads are secondary. Steady state: the
last simulated hour is compared to the quasi-analytical solution.

Run: python3 140_tests/scripts/generate_ae_reheat_cases.py
"""

import os

HERE = os.path.dirname(os.path.abspath(__file__))
CASES_DIR = os.path.join(os.path.dirname(HERE), "cases")

RHO = 1.215  # kg/m3 — air density that best centers results within the 7-program envelope
LAT1, LAT2 = 586.1, 879.2  # imposed zone latent gains [W]
V1, V2 = 0.28317, 0.33036  # zone design volume flows [m3/s]
M1, M2 = V1 * RHO, V2 * RHO  # zone design mass flows [kg/s]
OA_FRACTION = 0.3846  # (0.09439 + 0.14158) / (V1+V2) — fixed minimum outdoor-air fraction

# weather point per case (constant-condition EPW shared with the single-zone AE)
W = {101: "AE_m29", 103: "AE_155", 104: "AE_269", 105: "AE_249", 106: "AE_230"}

# case -> dict(z1=(sens,sp), z2=(sens,sp), w=weatherkey, econ, cv)
CASES = {
    # AE300 — constant-volume terminal reheat (min flow fraction 1.0)
    "AE301": dict(z1=(-2931.0, 21.111), z2=(-2345.0, 22.222), w=101, econ=None, cv=True),
    "AE303": dict(z1=(1465.0, 23.333), z2=(2345.0, 24.444), w=103, econ=None, cv=True),
    "AE304": dict(z1=(2931.0, 23.889), z2=(3517.0, 25.000), w=104, econ=None, cv=True),
    "AE305": dict(z1=(1465.0, 23.333), z2=(2345.0, 24.444), w=105, econ=None, cv=True),
    "AE306": dict(z1=(1465.0, 23.333), z2=(2345.0, 24.444), w=106, econ=None, cv=True),
    "AE326": dict(z1=(1465.0, 23.333), z2=(2345.0, 24.444), w=106,
                  econ="differential_dry_bulb", cv=True),
    "AE345": dict(z1=(1465.0, 23.333), z2=(2345.0, 24.444), w=105,
                  econ="differential_enthalpy", cv=True),
    # AE400 — VAV terminal reheat (zone min flow fractions 0.333 / 0.429)
    "AE401": dict(z1=(-2931.0, 21.111), z2=(-2345.0, 22.222), w=101, econ=None, cv=False),
    "AE403": dict(z1=(1465.0, 23.333), z2=(2345.0, 24.444), w=103, econ=None, cv=False),
    "AE404": dict(z1=(2931.0, 23.889), z2=(3517.0, 25.000), w=104, econ=None, cv=False),
    "AE405": dict(z1=(1465.0, 23.333), z2=(2345.0, 24.444), w=105, econ=None, cv=False),
    "AE406": dict(z1=(1465.0, 23.333), z2=(2345.0, 24.444), w=106, econ=None, cv=False),
    "AE426": dict(z1=(1465.0, 23.333), z2=(2345.0, 24.444), w=106,
                  econ="differential_dry_bulb", cv=False),
    "AE445": dict(z1=(1465.0, 23.333), z2=(2345.0, 24.444), w=105,
                  econ="differential_enthalpy", cv=False),
}

WALLS = [
    ("N", "wall", [(8, 6, 0), (0, 6, 0), (0, 6, 2.7), (8, 6, 2.7)]),
    ("S", "wall", [(0, 0, 0), (8, 0, 0), (8, 0, 2.7), (0, 0, 2.7)]),
    ("E", "wall", [(8, 0, 0), (8, 6, 0), (8, 6, 2.7), (8, 0, 2.7)]),
    ("W", "wall", [(0, 6, 0), (0, 0, 0), (0, 0, 2.7), (0, 6, 2.7)]),
    ("Roof", "roof", [(0, 0, 2.7), (8, 0, 2.7), (8, 6, 2.7), (0, 6, 2.7)]),
    ("Floor", "floor", [(0, 6, 0), (8, 6, 0), (8, 0, 0), (0, 0, 0)]),
]


def surfaces(case, zlabel):
    z = f"{case} {zlabel}"
    out = []
    for name, typ, v in WALLS:
        verts = ",".join(f"{{x: {x}.0, y: {y}.0, z: {zz}}}" for x, y, zz in v)
        out.append(f"  - {{name: {case} {zlabel} {name}, zone: {z}, type: {typ}, "
                   f"construction: Adiabatic Wall, boundary: adiabatic, vertices: [{verts}]}}")
    return "\n".join(out)


def make_yaml(case, c):
    z1n, z2n = f"{case} Zone1", f"{case} Zone2"
    (s1, sp1), (s2, sp2) = c["z1"], c["z2"]
    minfrac1 = 1.0 if c["cv"] else round(0.09439 / V1, 4)
    minfrac2 = 1.0 if c["cv"] else round(0.14158 / V2, 4)
    econ_block = ""
    if c["econ"]:
        econ_block = f"""      economizer:
        economizer_type: {c['econ']}
        high_limit: 24.0
"""
    return f"""# ASHRAE 140-2023 Section 11 — Case {case} ({'CV' if c['cv'] else 'VAV'} terminal reheat)
# GENERATED by 140_tests/scripts/generate_ae_reheat_cases.py.
# Two adiabatic zones, central preheat (7.22 C) + CHW cooling (fixed 12.78 C SAT)
# + supply/return fans, per-zone electric VAV:Reheat. Weather {W[c['w']]},
# economizer={c['econ']}. Steady-state; compare last hour to QAS central coils.

simulation:
  timesteps_per_hour: 1
  start_month: 1
  start_day: 1
  end_month: 1
  end_day: 7

weather_files:
  - "../weather/{W[c['w']]}.epw"

simple_constructions:
  - name: Adiabatic Wall
    u_factor: 0.01
    thickness: 0.01
    thermal_capacity: 0.0
    solar_absorptance: 0.1
    thermal_absorptance: 0.9
    roughness: rough

zones:
  - name: {z1n}
    volume: 129.6
    floor_area: 48.0
  - name: {z2n}
    volume: 129.6
    floor_area: 48.0

equipment:
  - {{name: {case} Z1 Sensible, zones: [{z1n}], power: {s1}, radiant_fraction: 0.0, latent_fraction: 0.0}}
  - {{name: {case} Z1 Latent, zones: [{z1n}], power: {LAT1}, radiant_fraction: 0.0, latent_fraction: 1.0}}
  - {{name: {case} Z2 Sensible, zones: [{z2n}], power: {s2}, radiant_fraction: 0.0, latent_fraction: 0.0}}
  - {{name: {case} Z2 Latent, zones: [{z2n}], power: {LAT2}, radiant_fraction: 0.0, latent_fraction: 1.0}}

surfaces:
{surfaces(case, 'Zone1')}
{surfaces(case, 'Zone2')}

air_loops:
  - name: SZ Air System
    system_type: vav
    min_vav_fraction: {min(minfrac1, minfrac2)}
    controls:
      heating_supply_temp: 40.0
      cooling_supply_temp: 12.78
      fixed_cooling_sat: true
      preheat_setpoint: 7.22
      cycling: proportional
      fan_operating_mode: continuous
      minimum_damper_position: {OA_FRACTION}
      minimum_oa_flow: 0.23597
      design_zone_flow: {round(M1, 5)}
      return_fan_pressure_rise: 249.0
      return_fan_total_efficiency: 0.7
{econ_block}    equipment:
      - type: heating_coil
        name: {case} Preheat Coil
        source: electric
        capacity: 30000.0
        efficiency: 1.0
        setpoint: 7.22
      - type: cooling_coil
        name: {case} Cooling Coil
        source: chilled_water
        capacity: 40000.0
        shr: 0.75
        rated_airflow: 0.61353
        setpoint: 12.78
        design_water_flow_rate: 0.003
        design_water_inlet_temp: 5.0
        design_water_outlet_temp: 12.0
        autocalculate_shr: true
      - type: fan
        name: {case} Supply Fan
        source: vav
        design_flow_rate: 0.61353
        pressure_rise: 498.0
        motor_efficiency: 1.0
        impeller_efficiency: 0.7
        motor_in_airstream_fraction: 1.0
    zone_terminals:
      - zone: {z1n}
        terminal:
          type: vav_box
          name: {case} Z1 Reheat
          max_air_flow: {round(M1, 5)}
          min_flow_fraction: {minfrac1}
          reheat_type: electric
          reheat_capacity: 20000.0
          max_reheat_temp: 60.0
          max_reheat_fraction: {minfrac1}
      - zone: {z2n}
        terminal:
          type: vav_box
          name: {case} Z2 Reheat
          max_air_flow: {round(M2, 5)}
          min_flow_fraction: {minfrac2}
          reheat_type: electric
          reheat_capacity: 20000.0
          max_reheat_temp: 60.0
          max_reheat_fraction: {minfrac2}

zone_groups:
  - name: {case} Z1 Group
    zones: [{z1n}]
  - name: {case} Z2 Group
    zones: [{z2n}]

thermostats:
  - name: {case} Z1 Thermostat
    zones: [{case} Z1 Group]
    heating_setpoint: {sp1}
    cooling_setpoint: {sp1}
  - name: {case} Z2 Thermostat
    zones: [{case} Z2 Group]
    heating_setpoint: {sp2}
    cooling_setpoint: {sp2}

outputs:
  - file: "hvac_results.csv"
    frequency: hourly
    variables:
      - "component:thermal_output"
      - "component:sensible_load"
      - "component:latent_load"
      - "component:total_load"
      - "component:outlet_temperature"
  - file: "zone_results.csv"
    frequency: hourly
    variables:
      - "zone:temperature"
      - "zone:humidity_ratio"

summary_report: true
"""


def main():
    for case, c in CASES.items():
        with open(os.path.join(CASES_DIR, f"ashrae140_case{case}.yaml"), "w") as f:
            f.write(make_yaml(case, c))
        print(f"wrote ashrae140_case{case}.yaml")


if __name__ == "__main__":
    main()
